const  Actions = {
    CREATE_TODO: 'CREATE_TODO',
    NAVIGATE_TO_DIFFERENT_PAGE: 'NAVIGATE_TO_DIFFERENT_PAGE',
    TODO_INPUT_CHANGE: 'TODO_INPUT_CHANGE',
    CLEAR_TODO_INPUT: 'CLEAR_TODO_INPUT',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO_BY_ID: 'DELETE_TODO_BY_ID',
    INCREMENT_LEN: 'INCREMENT_LEN',
    DECREMENT_LEN: 'DECREMENT_LEN',
    UPDATE_FILTER_TYPE: 'UPDATE_FILTER_TYPE'
}

export default Actions