const  Actions = {
    CREATE_TODO:'CREATE_TODO',
    NAVIGATE_TO_DIFFERENT_PAGE:'NAVIGATE_TO_DIFFERENT_PAGE',
    TODO_INPUT_CHANGE:'TODO_INPUT_CHANGE',
    CLEAR_TODO_INPUT:'CLEAR_TODO_INPUT',
    UPDATE_TODO:'UPDATE_TODO'
}

export default Actions